python/tk_multi_publish2/context_widget/context_widget.py

The "related" tasks background query was supposed to prevent unnecessary
SG queries by querying all fields required by `context.from_entity_dictionary`.
Unfortunately, the core docs had the field "name" instead of "context" and I
never tested to make sure that additional queries weren't happening. I've updated
the core docs separately and this adds the "context" field to the query which
appears to speed up the item selection.

#43803 Addresses publish2 slowness by preventing unnecessary queries

---

python/tk_multi_publish2/processing/item.py

Propably caused by copy-pasting

fixing AttributeError: 'Item' object has no attribute 'icon_pixmap'

---

python/tk_multi_publish2/dialog.py

When Publish items have multiple descriptions, a "multiple values" placeholder text is displayed in the summary description. When individual items are selected, this placeholder text is erroneously displayed too, while it should not appear for individual publish items.

#43896 Removed placeholder text in child items

---

python/tk_multi_publish2/dialog.py
python/tk_multi_publish2/summary_overlay.py
python/tk_multi_publish2/ui/summary_overlay.py
resources/summary_overlay.ui

Transformed the summary overlay status label into a clickable link that opens the log view.

42849 open log view from overlay

---

python/tk_multi_publish2/publish_tree_widget/custom_widget_context.py
python/tk_multi_publish2/publish_tree_widget/custom_widget_summary.py

Modified set_status() function arguments in CustomWidgetContext and CustomWidgetSummary to match the one in the base class (CustomTreeWidgetBase). This prevents additional errors from appearing in log file when an exception is launched during Publishing.

#42764 fixed some errors that appeared when exception is launched during publishing

---

python/tk_multi_publish2/dialog.py
python/tk_multi_publish2/processing/item.py
python/tk_multi_publish2/thumbnail.py

Implemented thumbnail inheritance
Items with default thumbnails are able to have override thumbnails set by the user
Implemented the equivalent to “Multiple Values” for thumbnail at the summary level that lets somebody know that they’d be overriding set thumbnails when they use that feature

#45629 Implemented thumbnail inheritance

---

hooks/publish_file.py
info.yml
python/tk_multi_publish2/dialog.py

* Add app config setting `validate_on_publish` (defaults to true)
* If this is `False`, then pressing publish will NOT run through validation.
* The app tracks if validation has been run, and if you are trying to publish without having validated, a UI pops up ensuring you wish to continue

#46000 Adds `validate_on_publish` boolean setting to allow skipping validation

---

python/tk_multi_publish2/__init__.py
python/tk_multi_publish2/base_hooks/__init__.py

Noticed some absolute imports in the publisher that are potentially dangerous - especially the `base_hooks` import is likely to overlap with other apps using `base_hooks`. @josh-t if you could take a quick look and check that this makes sense that would be great! thx!

Changed absolute imports to relative.

---

python/tk_multi_publish2/processing/item.py

Items that are added to publish after setting the summary thumbnail should not inherit summary thumbnail that was already set before. They should inherit it when the summary thumbnail is set after the items have been added.

#45629 thumbnail inheritance for items added to publish after setting summary thumbnail

---

python/tk_multi_publish2/dialog.py
python/tk_multi_publish2/summary_overlay.py

Adresses some minor issues + 1 regression found by QA:
- Hide progress bar in the no items error overlay
- Fix publish again button broken in previous commit
- Add 'More details' label in the no item error overly
- Add unconditionality the "Drag & drop disabled." to message log queue.

46405 add setting to disable content load2

---

hooks/publish_file.py
python/tk_multi_publish2/processing/item.py
tests/README.md
tests/fixtures/config/env/test.yml
tests/fixtures/config/hooks/collector.py
tests/fixtures/config/hooks/test_properties_plugin_1.py
tests/fixtures/config/hooks/test_properties_plugin_2.py
tests/fixtures/config/hooks/test_properties_plugin_3.py

This change adds a more granular interface to the base file publish plugin. Previously, publish properties such as `publish_type`, `publish_name`, and `publish_version` could only be injected into the publish item's `properties` dictionary as global values (shared by all attached plugins). The base plugin would key off of these to drive how to publish the item. This works fine when an item is being published by a single plugin. 
With these changes, a new `local_properties` property is available on collected items. This property acts like the regular `properties` but the values are stored for the current plugin only. It is now possible to set the `publish_*` values per-plugin, making it easier to build multi plugin publish workflows for a single item. 
Also, both `properties` and …

#46342 Adds publish file plugin instance publish properties

---

hooks/collector.py

Moves the old `COMMON_FILE_INFO` dictionary to a property. This makes it easy for clients to override these values without taking over the entire hook. 
Other tweaks were made to adjust for this dictionary being part of the instance such as:
- pre-calculating all the image types
- allowing subclasses to override the icons folder when calling the `_get_icon_path` convenience method.

#SG-5389 Makes common file info part of the collector API

---

python/tk_multi_publish2/publish_tree_widget/publish_tree_widget.py

JIRA: SMOK-48376
Follow-up to PR#72 (https://github.com/shotgunsoftware/tk-multi-publish2/pull/72)
It seem some more signals need to be connected in order for scrolling and selection to sync.

Workaround to make the scrollbar work properly for QT version 4 [2]

---

python/tk_multi_publish2/dialog.py

This fixes an intermittent bug where in some cases (especially with long running publishes), you would see this:
```
// Error: Shotgun dialog: Finalize error stack:
Traceback (most recent call last):
File "/shotgun/configs/defcon2/install/gitbranch/tk-multi-publish2.git/f38a7f8/python/tk_multi_publish2/dialog.py", line 709, in do_publish
self._visit_tree_r(parent, lambda child: child.finalize(), "Finalizing")
File "/shotgun/configs/defcon2/install/gitbranch/tk-multi-publish2.git/f38a7f8/python/tk_multi_publish2/dialog.py", line 753, in _visit_tree_r
for child_index in xrange(parent.childCount()):
RuntimeError: Internal C++ object (PySide2.QtWidgets.QTreeWidgetItem) already deleted.
```
It seems the parent handle for some reason is rendered invalid. This fix is simple - just reaqcuire the …

SG-4584 - Fix for intermittent GC problems

---

python/tk_multi_publish2/processing/plugin.py

JIRA: SMOK-48149
When publishing from Flame, we might publish multiple item and the message
Publish complete! will stay up for a while between each item published.
This is confusing for the user since the publish process might just be started.

Add item's name in publish completed! and finalize complete! messages

---

.gitignore
python/tk_multi_publish2/api/item.py
python/tk_multi_publish2/api/manager.py
python/tk_multi_publish2/api/tree.py
python/tk_multi_publish2/dialog.py
python/tk_multi_publish2/progress/publish_logging.py
tests/python/publish_api_test_base.py
tests/test_item.py
tests/test_manager.py
tests/test_tree.py

Fixes a bunch of issues with the publisher API.
This method originally validated that a given path was pointing to a loadable thumbnail, but didn't after the refactor. This caused issues in certain plugins like Photoshop. In Photoshop, when we publish the current scene we put the current file name as the thumbnail for the item. If the file is a psd, then it won't be loadable by QPixmap and the thumbnail will be ignored. If the file is a JPEG or any other regular image format the thumbnail is set successfully.
This behaviour has been repaired by adding back in the validation. To do so however, I've added extra code that make the API usable even if there is no QApplication instance. As such, the API can still be used when Qt isn't available.
During the original merge of the publish API, I …

For SG-7260, publish api fixes

---

docs/api.rst
python/tk_multi_publish2/api/manager.py
python/tk_multi_publish2/dialog.py
tests/test_item.py
tests/test_manager.py
tests/test_tree.py

In order to make the API more programmer centric, I've made the following changes:
- the validate phases will return a list of  tuples of (task, exception) of each validation that failes and not a list of items. This allows to know exactly what failed. If an exception was raised for that validation, it will be left as is
- the API will yield the exception that was raised and not just the text, so the generator can infer more from the error
- the publish and finalize methods now stop at first sign of an error, just like the GUI behaves. The exception is raised back to the caller.
- Because validation now reports the number of tasks that failed publish and not items that have failed tasks, it means the error count will be equal to the number of failed tasks and not equal to the number of …

For SG-7260, fixes the publish and finalize API flow

---

python/tk_multi_publish2/progress/progress_handler.py

I tweaked the error and warning colors to use the colors from the HIG. The icon colors match their text color now.

For SG-9236, publisher log colors

---

python/tk_multi_publish2/progress/ui/progress_details_widget.py
resources/progress_details_widget.ui

Sets a minimum width on one QToolButton to combat a styling problem we have in Houdini 17.

SG-9210: Resolves a QToolButton styling issue in Houdini 17.

---

hooks/publish_file.py
tests/fixtures/config/core/hooks/pick_environment.py
tests/fixtures/config/env/extra_fields_test.yml
tests/fixtures/config/hooks/extra_fields.py
tests/test_basic_publish_plugin.py

Update the publish hook to allow additional fields to be set on the publish through item properties.

SG-9941 Allow additional data to be included in publish publish

---

python/tk_multi_publish2/progress/publish_logging.py

This fix removes the 'block' that was previously in place in order to not bubble up log messages from the publish hooks to the official tk loggers (console and log files) but keep them only in the publish log console. 
This means that all logging generated by the publisher is now written to disk as well as to any log console that the engine implements, which makes things more consistent and makes troubleshooting and support easier.

SG-10273 Logging from publish console now bubbles up to std toolkit loggers

---

python/tk_multi_publish2/dialog.py

When `tk-multi-publish2` invokes the method `do_validate` it isn't passing the parameter value `is_standalone` explicitely. 
https://github.com/shotgunsoftware/tk-multi-publish2/blob/master/python/tk_multi_publish2/dialog.py#L120
In the method `do_validate`, the parameter `is_standalone` has `True` by default.
We found that in VRED 2019.X the value that arrives to this method is `True` but in VRED 2020.X is `False`.
According to multiple articles like this https://eli.thegreenplace.net/2011/04/25/passing-extra-arguments-to-pyqt-slot/
A workaround is to invoke the method using `lambda` function. We propose to change this invocation:
Current:
`self.ui.validate.clicked.connect(self.do_validate)`
Proposal:
`self.ui.validate.clicked.connect(lambda: self.do_validate())`

Fix do_validate invocation with a lambda function

---

hooks/collector.py
hooks/publish_file.py
hooks/upload_version.py

This PR adds support for PDF files.
It allows PDFs to be uploaded as versions which then become reviewable in Shotgun.
This will also generate a `PDF` `PublishedFileType` in SG when published.
Not sure if it should be shortened to PDF or expanded to Portable Document Format
Also I opted to classify the pdf as `file.image`, but perhaps a better classification would be `file.document`?

SG-8015 add support for PDF uploads

---

python/tk_multi_publish2/progress/progress_handler.py

The "Copy to Clipboard" action is no longer available in engines using PySide2 as the **QCoreApplication** class doesn't have a **clipboard** attribute anymore.
To be fully compatible with both PySide and PySide2, we're replacing the way we call the "clipboard()" method

SHOT-3115 Fixes an issue accessing the clipboard on PySide2

---

.gitignore
python/tk_multi_publish2/dialog.py

Sometimes a task is necessary for publishing an item.
For example:
`asset_root: assets/{sg_asset_type}/{Asset}/{task_name}`
When user clicks the button, the validation process detects the error 
and report it as expected.
We would like to offer users avoid having to wait for the validation 
process to correct this error.
We propose the following:
* A new optional setting `task_required` with a boolean value true/false
* If the setting exists and its value is true:
We call a new method inside `python/tk_multi_publish2/dialog.py`
named ``_validate_task_required`` which makes the next steps:
* Checks that a task is selected for every top item 
* Disables/Enables the validate and publish buttons 
* Change the color for the task label to RED or the default value
The call to …

Validates that a task is selected for every item if the setting task_required is true

---

python/tk_multi_publish2/api/tree.py
tests/test_tree.py

Fixes bug where a typo in the super call, meant super wasn't being passed an instance.
This meant you got an error if you tried to serialize a tree.

SG-14693 serialize tree bug fix

---

python/tk_multi_publish2/api/plugins/publish_plugin_instance.py

Fixes a bug where we accidentally tried to do UI specific logic only when a UI wasn't present.
So this reverses that logic to only do it when a UI is present.
I've also searched the code for other uses of `has_ui` as this is the second case of this, and all other ones appear to be correct.

SG-16766 Fixes a bug when a UI isn't present

---

python/tk_multi_publish2/publish_tree_widget/tree_node_item.py
python/tk_multi_publish2/publish_tree_widget/tree_node_task.py

Fixes an issue where when the state of an item or a task in the Publish UI is changed by the user, the Task or Item API object instances weren't updated to reflect this change.
We have another PR here #105, but this PR takes a different approach, and also fixes the task state as well.

SG-12136 Fixes Task and Item checkbox GUI state updates.

---

python/tk_multi_publish2/api/plugins/publish_plugin_instance.py
python/tk_multi_publish2/base_hooks/publish_plugin.py
python/tk_multi_publish2/dialog.py
tests/fixtures/config/hooks/plugin_with_ui.py
tests/test_publish_plugin_instance.py

This passes a list of `PublishItem`s associated with the selected publish tasks, through to the `create_settings_widget()` and `set_ui_settings()` methods, to allow users to customize the UI based upon the item details.
I opted not to pass the items through to the `get_ui_settings` method as I didn't really see a use case for that, but it could be easily added as well.

SG-10067 Passes selected publish tasks associated items to set/create UI methods.

---

style.qss

Remove publisher app style to set the progress bar background colour to be transparent.
This is for DCCs that have a different style theme than Toolkit's dark theme. If the progress bar background colour is transparent, it will show the widget behind it, in this case it will be the dialog window that inherits the QApplication's palette Window attribute. This only works for DCCs that have a theme that is consistent with Toolkit.
For example, SketchBook has a light theme and the progress bar will show up as white, instead of the desired darker grey colour.
Tested with Maya, and this change has no effect on the progress bar colour.

[SHOT-3575] Fix Qt style for light themed DCCs

---

app.py
hooks/pre_publish.py
info.yml
python/tk_multi_publish2/__init__.py

The current workflow for publishing when file has not been saved yet:
1. Open publish dialog and plugins are accepted -- may yield warning message in logs that file requires saving first
2. On validate or publish, an error is reported if file has not yet been saved. In some engines, a `Save As` button appears next to the error in the publish log UI
3. User clicks `Save As` to save file and then they can continue to publish
We're proposing to improve this workflow:
1. Before opening the publish dialog, run a pre-publish hook to determine if user can proceed to publishing or not
2. Default to Yes the user can proceed. Engine's may define custom pre-publish hook logic.
Also, for SketchBook we want the option to open the publish dialog as a modal window -- so we've added a settings option …

[SKB-2333] Prompt user to save work  before opening publish dialog

---

azure-pipelines.yml
tests/test_gui.py

Adding Azure Agent Name to Shotgun project name.
Like that, the Shotgun project will not be overwritten when we will run the UI automation on both, Python 2 and 3

Adding Azure Agent Name to Shotgun project name

---

python/tk_multi_publish2/api/manager.py

One extra bit of cleanup was also done, just for consistency. The bug crops up when there are multiple instances of the publish2 app in the same engine/environment, and when the publish context is different than the parent bundle context. Note that I did not reproduce the specific error raised, but I did confirm that the bug existed by inspecting the structure of the data returned by `sgtk.platform.engine.find_app_settings` along with the obvious difference in logic between lines 543 and 545, which obviously shouldn't be different considering they're indexing into the same data structure as one another.

SG-21329: Incorporates changes from client PR #99

---

app.py

When creating a publish manager, provide a custom logger to be able to get the hook log entries in an easy way

[SHOT-3860] Provide logger when creating publish manager

---

python/tk_multi_publish2/api/item.py
tests/test_item.py

This is a rebased version of #141.
It is not possible to merge #141 as-is unfortunately because:
- The branch is 18 months old
- The branch it is based on does not work with the current SG version.
- The PR checks did not pass and I am unable to re-run them
The code change, after rebasing, works and fixes the original issue: it prevents Nuke from crashing when running in terminal-only mode.
Reproduced on both Nuke versions 12 and 14.

SG-25264 Prevent Nuke crash when the app is being used in terminal only mode (no ui)

---

.gitignore
python/tk_multi_publish2/publish_tree_widget/custom_widget_task.py
python/tk_multi_publish2/publish_tree_widget/publish_tree_widget.py
python/tk_multi_publish2/publish_tree_widget/tree_node_task.py

This PR addresses the issue where is impossible to check back on the hidden (`visibility: False`) publish plugins. When any plugin is checked ✅ , all invisible plugins are also checked under the hood.
- Adds a new flag to invoke a method similar to `set_check_state_for_all_plugins` that walks the tree and activate invisible plugins.
- Updates .gitignore with vscode directory

SG-20984 Check hidden tree items on Publish dialog

---

python/tk_multi_publish2/api/item.py

When we're using the Publish API to publish items, and if the item has a thumbnail path specified, it is not taken into account. We should be able to use it even in batch mode because we don't have to deal with QT as it's only a path, not an image

[SHOT-4192] Add the possibility to specify a thumbnail when publishing using the API

---

python/tk_multi_publish2/api/data.py

Deprecated since version 3.3, will be removed in version 3.10: Moved [Collections Abstract Base Classes](https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes) to the [collections.abc](https://docs.python.org/3.9/library/collections.abc.html#module-collections.abc) module. For backward compatibility, they continue to be visible in this module through Python 3.9.
Ref. https://docs.python.org/3.9/library/collections.html
This PR 
Resolves #163 
Resolves #167

SG-30075 address python 3 10 deprecation collections

---

hooks/publish_file.py

- Follow up work from #151 
- There are cases on custom plugins when `path` is stored under `local_properties`. This update prevent the publish plugin from breaking on `finalize` step.

SG-29238 Prevent AttributeError when path is missing

---

hooks/collector.py
hooks/upload_version.py

* When PDF files are categorized as 'file.image', the pdf file path is used as the thumbnail; however the ShotGrid REST API request upload/api_link_file cannot handle a PDF file (must be an image), thus causing an API error
* Fix publishing PDF files by categorizing them as their own file type 'file.pdf'.
* Thumbnail for Published File is only uploaded if user uses the screen grab (not auto generated as it tried before). The Version will get a thumbnail auto generated (via uploading to the sg_uploaded_movie field)

SG-32840: Fix for publishing PDF files

---

hooks/collector.py
hooks/thumbnail_generator.py
info.yml
python/tk_multi_publish2/dialog.py
python/tk_multi_publish2/thumbnail.py
python/tk_multi_publish2/util.py

* Auto generate a thumbnail for standalone Desktop publishing
* Supported for Alias and VRED out of the box.
* Hook added to allow to extending support for other DCCs

SHOT-3829/SHOT-4303:  Alias/VRED auto generate thumbnail for standalone publish

---

python/tk_multi_publish2/publish_tree_widget/custom_widget_item.py
python/tk_multi_publish2/publish_tree_widget/custom_widget_task.py

This PR addresses an issue where the `stateChanged` signal from `QCheckBox` was emitting an integer type instead of a `Qt.CheckState` enum. This anomaly was leading to unexpected behavior where the Publish App UI checkboxes could not be checked properly. To ensure compatibility and maintain the expected behavior across PySide2 and PySide6, this explicitly convert the emitted integer to a `Qt.CheckState` enum within the slot that handles checkbox state changes.
- Updated the `_on_checkbox_click` slot method to check if the `state` argument is an instance of `int`.
- If an integer value  is received as status, it is converted to the corresponding `Qt.CheckState` enum using `Qt.CheckState(state)`.
Closes #180 
Closes #184

SG-33587 QT6 Maya Beta: The Checkboxes in the Publish Window Do Not Work

---

hooks/upload_version.py

* This will show the Upload Version plugin for .avi files

SHOT-4365: Update upload version plugin to include .avi files

---

.pre-commit-config.yaml
hooks/collector.py
python/tk_multi_publish2/api/item.py
python/tk_multi_publish2/api/task.py
python/tk_multi_publish2/dialog.py
python/tk_multi_publish2/progress/progress_handler.py
python/tk_multi_publish2/settings_widget.py
tests/fixtures/configInheritance/hooks/collector.py

* Currently the Background Publishing option can only be turned on/off by the config settings
* Add checkbox to publish app UI to make it more convenient for users to turn background publishing on/off
* Use the existing Settings widget in the publish app (currently just hidden) to show the new background publish option
* The background publish option will only show up when the current running engine supports background publishing (e.g. has tk-multi-bg-publish app configured)

SHOT-4411: Add UI settings option for Background Publishing
